### ISSUE TITLE
DSE cluster creation fails silently

### ISSUE THREAD

**Issue by tom-kuppinen-datastax** [jamesc127/datastax-enterprise-cdc-demo#1]
I was able to get this demo up and running in early Jan 2021 but trying this again today, the DSE cluster doesn't seem to be created.  I've tried debugging a bit and the only hint I can find is 
```
 helm install -f ./datastax_enterprise/cass-operator-values.yaml cass-operator datastax/cass-operator
W0107 15:08:19.848154   47715 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0107 15:08:20.457794   47715 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
W0107 15:08:21.176312   47715 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0107 15:08:21.994030   47715 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
```

**Comment by jamesc127** [comment]
hey @tom-kuppinen-datastax ! I'm going to run it and see if I get the same results here. Will update later this morning.

**Comment by jamesc127** [comment]
@tom-kuppinen-datastax , I was able to deploy the entire demo this morning by using the scripts. I did get the same output as you did when the `helm install` command was run to install the cass-operator. This however isn't when the DSE cluster is deployed. The next command in the script is the command that actually uses the operator and deploys the cluster.
```bash
  kubectl apply -f ./datastax_enterprise/deploy-cassandra.yaml
```
Would you mind giving it another go and let me know if the above command is able to deploy the cluster?

**Comment by tom-kuppinen-datastax** [comment]
@jamesc127 I just tried and it did work.  Apologies for any false alarm, still learning how all this works and not sure why it failed yesterday.  thank you for your help
