### ISSUE TITLE
GKE Cluster Version Needs to be Updated

### ISSUE THREAD

**Issue by beaubush-datastax** [jamesc127/datastax-enterprise-cdc-demo#4]
diff --git a/00-deploy-gke.sh b/00-deploy-gke.sh
index 0727510..14950c6 100755
--- a/00-deploy-gke.sh
+++ b/00-deploy-gke.sh
@@ -5,7 +5,7 @@ GCP_ZONE=$3
 
 create_k8s_cluster(){
   gcloud beta container --project "$PROJECT_NAME" clusters create "$K8S_CLUSTER_NAME" --zone "$GCP_ZONE" --no-enable-basic-auth \
-  --cluster-version "1.21.9-gke.1001" --release-channel "None" --machine-type "e2-standard-8" --image-type "COS_CONTAINERD" \
+  --cluster-version "1.21.11-gke.1100" --release-channel "None" --machine-type "e2-standard-8" --image-type "COS_CONTAINERD" \
   --disk-type "pd-standard" --disk-size "100" --metadata disable-legacy-endpoints=true \
   --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
   --max-pods-per-node "110" --num-nodes "3" --logging=SYSTEM,WORKLOAD --monitoring=SYSTEM --enable-ip-alias \00-deploy-gke.sh currently uses cluster version 1.21.9 and will not deploy. Changing it to 1.21.11 resolves the issue.

**Comment by jamesc127** [comment]
Fixed by #6
